### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by RemainsMods** [MobBotTeam/PokeMobBot#622]
i know this isnt really an issue, but i want to know if there is like a discord chat or skype chat that people share the locations of pokemons. so when the bot comes back up we can all help each other out..

**Comment by IInsomnia** [comment]
There is a Discord chat and Forum for PokeMobBot
Heres the link http://forum.pokemobbot.com

**Comment by kalpino** [comment]
Hello, juste if you want to see pokemons, https://skiplagged.com/pokemon/ is back !!
