### ISSUE TITLE
Suggestion: Update where the bot states it is down

### ISSUE THREAD

**Issue by Kampfhamster** [MobBotTeam/PokeMobBot#624]
Hello guys,
after all the request why the bot is not working/no pokestops found are triggering/filling the issue section, an update where the exe prompts, that the bot is currently not working/linking on the reamde.md, would unstress issue coming in because the ppl dont read the readme

Some examples(#623 #618 #621 #619 )

**Comment by chopraaa** [comment]
Let them stress. This isn't proprietary software.

**Comment by antfuentes87** [comment]
Another useless issue, close this.
