### ISSUE TITLE
Every Time I Try, I Get Spammed With This

### ISSUE THREAD

**Issue by Arubberband1** [MobBotTeam/PokeMobBot#625]
I've tried using a GPX (didn't know how to set it up)
I've tried changing my coordinates (didn't work)

Any suggestions? 
![ss 2016-08-05 at 08 06 18](https://cloud.githubusercontent.com/assets/20867957/17453579/175a165c-5b4c-11e6-9f87-eb4bc34e872b.png)

**Comment by DrAsphyxia** [comment]
read the other 500 threads made please

**Comment by joeyd55** [comment]
Really?? Must be using Internet Explorer

**Comment by DrAsphyxia** [comment]
#618
