### ISSUE TITLE
how to get PokeMobBot working on mac/ios?

### ISSUE THREAD

**Issue by withasideof2j** [MobBotTeam/PokeMobBot#629]
does anyone have this working on iOS? I'm running OS X El Capitain, and am unable to find a way to get this working, any help is greatly appreciated

**Comment by Mellanfil** [comment]
Really? REALLY? You don't see the other 42342 posts? Or the readme? Or the post right under your post?

**Comment by LNSDISCORDER** [comment]
@Mellanfil  this is why i have little faith in humanity. With so many dumbed down, stupid fucking lazy idiots that make up the majority.

**Comment by Kampfhamster** [comment]
@withasideof2j use parallels or another vm(works fine), ios is the iphone/ipad operatin system, so where is the use for the bot on a cellphone.

**Comment by withasideof2j** [comment]
@Kampfhamster isn't parallels a pay to use vm?

**Comment by Kampfhamster** [comment]
@withasideof2j I like it more  than v.Box

**Comment by HEADH0NCH0** [comment]
No need to be so hostile. 

You're going to have to use a virtual machine, preferably parallels. I use it on my mac and it's great.
