### ISSUE TITLE
Not totally an ISSUE , read first.

### ISSUE THREAD

**Issue by HugoMSantos** [MobBotTeam/PokeMobBot#632]
Hi there!
There's a guy on Youtube trying to gain money with surveys!
And using "PokeMobBot" outdated version to people think thats real.
video link - https://www.youtube.com/watch?v=O2-4oZyaWwg

**Comment by Denuvo** [comment]
Thank you for bringing this up to us.
I'll be taking action against the video.
It should be removed soon enough.

**Comment by ShallowHacker** [comment]
I watched the video and it's not PokeMob...? But ok
