### ISSUE TITLE
The only currently working bot

### ISSUE THREAD

**Issue by XxDdosingDosaxX** [MobBotTeam/PokeMobBot#637]
.

**Comment by XxDdosingDosaxX** [comment]
![screenshot_20160806232107](https://cloud.githubusercontent.com/assets/20882674/17460444/a8886d14-5c2c-11e6-9c60-5b3f4946d226.jpg)

**Comment by cameron1015** [comment]
i just downloaded but what is the auth. tab? is that where you enter ur login details?

**Comment by XxDdosingDosaxX** [comment]
auth is where you put: TH3CRACKED
