### ISSUE TITLE
Not working -> NecroBot

### ISSUE THREAD

**Issue by janssen92** [MobBotTeam/PokeMobBot#643]
For everyone that didnt know before: This is only a stolen and rebranded Version from NecroBot.

Luckily, NecroBot is already running again, checkout: https://github.com/NECROBOTIO/NecroBot

**Comment by globus243** [comment]
it was forked, not stolen. and check out their twitter, they're trying to implement a ban proof way which necrobot hasn't. atm it's risky to use necro.

**Comment by Kalashnikitty** [comment]
lol what a cunt
